# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Study/CODE/Mywork/MulCPU/MulCPU.cache/wt [current_project]
set_property parent.project_path D:/Study/CODE/Mywork/MulCPU/MulCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Study/CODE/Mywork/MulCPU/MulCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/ADR.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/ALU.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/ALUuotDR.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/BDR.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/ControlUnit.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/DBDR.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/DataMemory.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/IR.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/InstructionMemory.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/Mux_Threee_To_OneReg.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/Mux_Two_To_One_A.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/Mux_Two_To_One_B.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/NextPC.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/PC.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/RegisterFile.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/Sign_Zero_Extend.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/WriteSelect.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/WriteSelect1.v
  D:/Study/CODE/Mywork/MulCPU/MulCPU.srcs/sources_1/new/RunCPU.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top RunCPU -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RunCPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RunCPU_utilization_synth.rpt -pb RunCPU_utilization_synth.pb"
